apiVersion: apps/v1
kind: Deployment
metadata:
 name: httpd-deploy
spec:
 replicas: 2
 selector:
  matchLabels:
   app: apache
 template:
  metadata:
   labels:
    app: apache
  spec:
   containers:
   - image: httpd:latest
     name: apache-httpd
     ports:
     - containerPort: 8080
     env:
     - name: PROJECT_ID
       valueFrom:
        configMapKeyRef:
         name: project-config
         key: project.id
