apiVersion: apps/v1
kind: Deployment
metadata:
 name: httpd-deploy
spec:
 replicas: 2
 selector:
  matchLabels:
   app: apache
 template:
  metadata:
   labels:
    app: apache
  spec:
   containers:
   - image: httpd:latest
     name: apache-httpd
     ports:
     - containerPort: 8080
     env:
     - name: WEBLOGIC_ID
       valueFrom:
        secretKeyRef:
         name: api-key
         key: was
     - name: WEBLOGIC_PASS
       valueFrom:
        secretKeyRef:
         name: api-key
         key: pass
     - name: DBUSER
       valueFrom:
        secretKeyRef:
         name: api-key
         key: dbuser
     - name: DBPASS
       valueFrom:
        secretKeyRef:
         name: api-key
         key: dbpass
