apiVersion: apps/v1
kind: Deployment
metadata:
 name: helloworld-deployment
spec:
 selector:
  matchLabels:
   app: helloworld
 replicas: 2
 template:
  metadata:
   labels:
    app: helloworld
  spec:
   containers:
   - name: helloworld
     image: iad.ocir.io/idcollxtpgky/helloworld:latest
     ports:
     - containerPort: 80
   imagePullSecrets:
   - name: ocirsecret
