apiVersion: v1
kind: Pod
metadata:
 name: stress
 namespace: oke-xers9
spec:
 containers:
 - name: heavy-resource
   image: polinux/stress
   command: ["stress"]
   args: ["--vm", "1", "--vm-bytes", "900M", "--vm-hang", "1"]

