apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: nginx-rs
spec:
 replicas: 3
 selector:
  matchLabels:
   appName: nginx-app
 template:
  metadata:
   labels:
    appName: nginx-app
    env: TEST
  spec:
   containers:
   - image: nginx:latest
     name: nginx-container
     ports:
      - containerPort: 80
