apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-web-deployment

spec:
 replicas: 2
 selector:
  matchLabels:
    app: nginx-view

 template:
  metadata:
   labels:
    app: nginx-view
    env: stage
  spec:
   containers:
   - image: nginx:1.17.6
     name: nginx-container
     ports:
     - containerPort: 80
