apiVersion: v1
kind: Pod
metadata:
 name: liveness-www
 labels:
  name: nginx
  method: Pod
  liveness: http
spec:
 containers:
 - name: liveness
   image: nginx
   ports:
    - containerPort: 80
   livenessProbe:
    httpGet:
     path: /
     port: 8080
    initialDelaySeconds: 10
    periodSeconds: 5
   resources:
    requests:
     cpu: 800m
     memory: 8G
 restartPolicy: OnFailure
