apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-web-deployment

spec:
 replicas: 3
 selector:
  matchLabels:
    app: nginx-web

 template:
  metadata:
   labels:
    app: nginx-web
  spec:
   containers:
   - image: nginx:latest
     name: nginx-container
     ports:
     - containerPort: 80
